### ISSUE TITLE
An Internal Error

### ISSUE THREAD

**Issue by MaroonOnix** [Xquiset/SetHomes#16] opened 2020-12-16 16:55 UTC
I love using the plug-in, but one of the players on my server is having a recurring problem. They can set a default home with no issue and can teleport freely using the /home and /home-to commands, but when they try making a new home with a name, I.E. /sethome mineshaft, a message pops up for them saying "An internal error has occurred while attempting to perform this command." The player has OP status and other players with lesser permissions are able to use the command freely. Whatmore, nothing shows up in the server console indicating an error ever occurred. Any help would be greatly appreciated.

**Comment by Xquiset** [comment] 2020-12-16 20:24
Hello,
I am sorry you're experiencing this issue. Could you please find the UUID of the player and post it here along with a copy of your homes.yml file? The player UUID should be displayed in the console every time a player joins. The homes.yml is located in plugins > SetHomes > homes.yml
Best Regards,
Xquiset

**Comment by ThatOneJay** [comment] 2020-12-28 09:37
Heyo,
having similar issues. One of my players has this issue while everyone else is fine.

The error says:

```
[20:22:35] [Server thread/ERROR]: null
--
org.bukkit.command.CommandException: Unhandled exception executing command 'h' in plugin SetHomes v1.2.9
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-343]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-343]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.4.jar:git-Paper-343]
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[patched_1.16.4.jar:git-Paper-343]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.4.jar:git-Paper-343]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.4.jar:git-Paper-343]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-343]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-343]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-343]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-343]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-343]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-343]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-343]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-343]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-343]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.4.jar:git-Paper-343]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1262) ~[patched_1.16.4.jar:git-Paper-343]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-343]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-343]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
at com.samleighton.xquiset.sethomes.SetHomes.getHomeLocaleFromConfig(SetHomes.java:370) ~[?:?]
at com.samleighton.xquiset.sethomes.SetHomes.getPlayersNamedHomes(SetHomes.java:231) ~[?:?]
at com.samleighton.xquiset.sethomes.commands.GoHome.teleportHome(GoHome.java:177) ~[?:?]
at com.samleighton.xquiset.sethomes.commands.GoHome.onCommand(GoHome.java:56) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-343]
... 19 more
```

**Comment by JonathanBerkeley** [comment] 2020-12-29 02:59
It's likely caused by the player using a decimal point in the name of their home. 
You can manually remove the last home for the glitched player from the homes.yml file, then the player should be able to use their 
other sethomes as normal.

You are running version 1.2.9, latest version as of writing is 1.3.0, which fixes this issue. Using 1.3.0 requires either downloading this repository and compiling it yourself, or waiting for the compiled jar to be approved by Bukkit. Until then tell your players to avoid using decimal points in their home names.

**Comment by ThatOneJay** [comment] 2020-12-29 04:17
The player facing this issue does not have any decimal points in any of their homes, and started happening when they used a home in the End. All homes do not work expect for just /home (default home) and /back.
``` efb8fb9b-7338-430c-adb8-43eeb6e5e131:
    n:
      world: world
      x: 86.7253912573427
      y: 58.0
      z: 85.85330499458058
      pitch: 23.275343
      yaw: -55.15381
    j:
      world: world
      x: -44.184223154210386
      y: 60.5
      z: 246.69999998807907
      pitch: 11.577396
      yaw: 157.29913
    a:
      world: world
      x: -230.30000001192093
      y: 115.0
      z: 141.30000001192093
      pitch: 18.053804
      yaw: -312.84338
    e:
      world: world_the_end
      x: 5171.707526832216
      y: 99.0
      z: 311.70395955086684
      pitch: 14.740844
      yaw: 357.08286
    z: 589.1420405832525
    ee:
      world: world_the_end
      x: 17.565712310704463
      y: 63.0
      z: 2.3944954349921277
      pitch: 5.759144
      yaw: -261.5432
    c:
      world: world
      x: 123.73271785603065
      y: 210.0
      z: 445.92003514240884
      pitch: 36.330395
      yaw: 39.101337
    v:
      world: world
      x: 84.307344084891
      y: 11.0
      z: 86.67728686005682
      pitch: 18.048458
      yaw: -153.28741
    u:
      world: world
      x: 1636.300000011921
      y: 67.5625
      z: 124.30000001192093
      pitch: 21.630547
      yaw: -40.30563
    xp:
      world: world_the_end
      x: 215.35012071226808
      y: 1.0
      z: 67.72601318135843
      pitch: 12.170492
      yaw: 220.6429
    i:
      world: world
      x: -4598.300000011921
      y: 42.0
      z: 1334.562459951592
      pitch: 7.2371073
      yaw: 94.60515
    vv:
      world: world
      x: -9179.300000011921
      y: 66.0
      z: 1326.8102150192863
      pitch: 13.714484
      yaw: 115.66284
    vvv:
      world: world
      x: -9581.699999988079
      y: 70.0
      z: 1166.300000011921
      pitch: 28.519445
      yaw: -50.120483
    s:
      world: world
      x: -12743.780964178208
      y: 63.0
      z: 992.47545241023
      pitch: -2.323157
      yaw: -264.07404
    vvvv:
      world: world
      x: -15724.300000011921
      y: 64.0
      z: 1211.5716577636726
      pitch: 12.788673
      yaw: 90.005775
    vvvvv:
      world: world
      x: -17091.30000001192
      y: 65.0
      z: 1321.699999988079
      pitch: 22.864424
      yaw: -246.54166

**Comment by ThatOneJay** [comment] 2020-12-29 04:38
Aight, I found the issue.

First off, there was a home in the file without any details for it, so I got rid of that. Still had the same issue. I went through his worlds and found a random z-axis randomly placed within the file. Got rid of that so now it's working.

**Comment by JonathanBerkeley** [comment] 2020-12-29 07:52
> Aight, I found the issue.
> 
> First off, there was a home in the file without any details for it, so I got rid of that. Still had the same issue. I went through his worlds and found a random z-axis randomly placed within the file. Got rid of that so now it's working.

Good to hear it's working now. Non-alphanumerical characters in the home name cause this error also. (The home will save incorrectly into the file, editing it as you did is the easiest fix. Possibly instruct your players to only use alphanumeric names for their homes until 1.3.0 becomes available on bukkit)

**Comment by Xquiset** [comment] 2021-01-15 01:08
Hello,

I am aware that this issue has been resolved therefore I am going to close this ticket. V1.3.0 of SetHomes has been accepeted by Bukkit and is now available to the public on the project page.

Best Regards,
Xquiset

**Closed as completed by Xquiset** 2021-01-15 01:08 UTC
